---
# tasks file for role/basepath
- name: Ensure basepath directory exists [{{ basepath_dir }}]
  ansible.builtin.file:
    path: "{{ basepath_dir }}"
    state: directory
    mode: "0755"
    owner: root
    group: root
