---
# defaults file for role/dhcp
dhcp_lan_ip: "{{ server_lan_ip }}"
dhcp_lan_net: "{{ server_lan_net }}"
dhcp_lan_netmask: "{{ server_lan_netmask }}"
dhcp_lan_interface: "{{ server_lan_interface }}"
# dhcp_lan_ip_pool_start: 192.168.192.99
# dhcp_lan_ip_pool_end: 192.168.192.199
