---
# tasks file for role/iso-linuxmint

- name: Ensure LinuxMint root directory exists [{{ iso_linuxmint_basepath_dir }}]
  ansible.builtin.file:
    path: "{{ iso_linuxmint_basepath_dir }}"
    state: directory
    mode: '0755'
    owner: root
    group: root

# - name: Ensure LinuxMint ISO mount point exists [{{ iso_linuxmint_basepath_dir }}/iso]
#   ansible.builtin.file:
#     path: "{{ iso_linuxmint_basepath_dir }}/iso"
#     state: directory
#     mode: '0755'
#     owner: root
#     group: root

- name: Get status of ISO {{ iso_linuxmint_filename }}
  ansible.builtin.stat:
    path: "{{ iso_linuxmint_basepath_dir }}/{{ iso_linuxmint_filename }}"
    get_attributes: false
    get_checksum: false
    get_mime: false
  register: iso_file_status

# - name: Check if ISO file is missing
#   ansible.builtin.set_fact:
#     iso_file_missing: "{{ not iso_file_status.stat.exists }}"
#   changed_when: iso_file_missing

- name: Stop NFS service
  ansible.builtin.systemd_service:
    name: nfs-server
    state: stopped
  register: nfs_stop_result
  when: iso_file_status.stat.exists

- name: Umount ISO {{ iso_linuxmint_filename }}
  ansible.posix.mount:
    path: "{{ iso_linuxmint_basepath_dir }}/iso"
    state: unmounted
  when: iso_file_status.stat.exists and nfs_stop_result.state == "stopped"

- name: Copy preseed files
  ansible.builtin.copy:
    src: files/
    dest: "{{ iso_linuxmint_basepath_dir }}/"
    owner: root
    group: root
    mode: '0644'

- name: Mount ISO {{ iso_linuxmint_filename }}
  ansible.posix.mount:
    path: "{{ iso_linuxmint_basepath_dir }}/iso"
    src: "{{ iso_linuxmint_basepath_dir }}/{{ iso_linuxmint_filename }}"
    fstype: auto # usually iso9660 but win use udf so: auto
    opts: ro
    state: mounted

- name: Ensure mint.ipxe is not present anymore
  ansible.builtin.file:
    path: "{{ iso_linuxmint_basepath_dir }}/mint.ipxe"
    state: absent
