---
galaxy_info:
  author: Andrea Perotti
  description: apt update cache if it is older than 1 day
  company: Associazione PCOfficina

  license: GPL-3.0-only

  min_ansible_version: '2.16'

  # If this a Container Enabled role, provide the minimum Ansible Container version.
  # min_ansible_container_version:

  platforms:
    # - name: EL
    #   versions:
    #     - "8"
    #     - "9"
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: Debian
      versions:
        - buster
        - bullseye

  galaxy_tags:
    - apt
    - debian
    - ubuntu
    - update
    - cache

dependencies: []
