galaxy_info:
  author: Andrea Perotti <aperotti@pcofficina.org>
  description: Pcofficina.Netinstaller Run Role
  company: Associazione PCOfficina

  # If the issue tracker for your role is not on github, uncomment the
  # next line and provide a value
  # issue_tracker_url: http://example.com/issue/tracker

  license: GPL-3.0-only

  min_ansible_version: "2.14"

  # If this a Container Enabled role, provide the minimum Ansible Container version.
  # min_ansible_container_version:

  #
  # Provide a list of supported platforms, and for each platform a list of versions.
  # If you don't wish to enumerate all versions for a particular platform, use 'all'.
  # To view available platforms and versions (or releases), visit:
  # https://galaxy.ansible.com/api/v1/platforms/
  #
  # platforms:
  # - name: Fedora
  #   versions:
  #   - all
  #   - 25
  # - name: SomePlatform
  #   versions:
  #   - all
  #   - 1.0
  #   - 7
  #   - 99.99

  galaxy_tags:
    []
    # List tags for your role here, one per line. A tag is a keyword that describes
    # and categorizes the role. Users find roles by searching for tags. Be sure to
    # remove the '[]' above, if you add tags to this list.
    #
    # NOTE: A tag is limited to a single word comprised of alphanumeric characters.
    #       Maximum 20 tags per role.

dependencies:
  - role: pcofficina.netinstaller.debian_only
  - role: pcofficina.netinstaller.apt_update_cache
  - role: pcofficina.netinstaller.basepath
  - role: pcofficina.netinstaller.network
  - role: pcofficina.netinstaller.dhcp
  - role: pcofficina.netinstaller.router
  - role: pcofficina.netinstaller.memtest
  - role: pcofficina.netinstaller.iso_linuxmint
  - role: pcofficina.netinstaller.iso_win11
  - role: pcofficina.netinstaller.ipxe
  - role: pcofficina.netinstaller.tftp
  - role: pcofficina.netinstaller.nfs
  - role: pcofficina.netinstaller.samba
  - role: pcofficina.netinstaller.http
