---
# tasks file for role/network

- name: Install NetworkManager
  ansible.builtin.apt:
    package: network-manager
    state: latest

- name: Reconfigure traditional network stack
  ansible.builtin.copy:
    src: files/interfaces
    dest: /etc/network/interfaces
    mode: "0644"

- name: Ensure NetworkManager is running
  ansible.builtin.service:
    name: NetworkManager
    enabled: true
    state: started

- name: Add an Ethernet connection with static IP configuration for  "{{ network_lan_interface }}"
  community.general.nmcli:
    conn_name: "{{ network_lan_interface }}"
    ifname: "{{ network_lan_interface }}"
    type: ethernet
    ip4: "{{ network_lan_ip }}/{{ network_lan_netmask }}"
    # gw4: "" # this interface IS the GW
    never_default4: true
    state: present

- name: Enable connection for  "{{ network_lan_interface }}"
  ansible.builtin.command:
    cmd: nmcli connection up "{{ network_lan_interface }}"
  register: network_nmcli_output # <- Registers the command output.
  changed_when: network_nmcli_output.rc != 0 # <- Uses the return code to define when the task has changed.
