---
# tasks file for roles/memtest
- name: Ensure memtest root directory exists [{{ memtest_basedir }}]
  ansible.builtin.file:
    path: "{{ memtest_basedir }}"
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Get memtest archive with checksum url (sha256)
  ansible.builtin.get_url:
    url: "{{ memtest_archive_url }}"
    dest: "{{ memtest_basedir }}"
    checksum: "sha256:{{ memtest_archive_sha256 }}"
    mode: '0644'

- name: Install zip
  ansible.builtin.apt:
    package: zip
    state: latest

- name: Extract memtest exes {{ memtest_exes }}
  ansible.builtin.unarchive:
    src: "{{ memtest_basedir }}/{{ memtest_archive_name }}"
    dest: "{{ memtest_basedir }}"
    remote_src: true
    include: "{{ memtest_exes }}"
