---
# tasks file for role/dhcp
- name: Install Kea DHCPv4 server
  ansible.builtin.apt:
    package: kea-dhcp4-server
    state: latest
    install_recommends: false
    fail_on_autoremove: true

- name: Check if AppArmor specific file exist
  ansible.builtin.stat:
    path: "{{ apparmor_conf }}"
  register: apparmor_state

# - name: Ensure hook is present in {{ apparmor_conf }}
#   ansible.builtin.lineinfile:
#     path: "{{ apparmor_conf }}"
#     line: '/etc/kea/** r,'
#     state: present
#     create: false
#   when: apparmor_state.stat.exists

- name: Ensure kea can read temp conf file from ansible temp dir
  ansible.builtin.blockinfile:
    path: "{{ apparmor_conf }}"
    block: |
      /root/.ansible/tmp/ r,
      /root/.ansible/tmp/** r,
    marker: "### {mark} ANSIBLE MANAGED BLOCK"
    insertbefore: '}'
  when: apparmor_state.stat.exists
  notify: Reload AppArmor

- name: Force all notified handlers to run at this point, not waiting for normal sync points
  ansible.builtin.meta: flush_handlers

- name: Deploy Kea DHCPv4 server configuration
  ansible.builtin.template:
    src: templates/kea-dhcp4.conf.j2
    dest: /etc/kea/kea-dhcp4.conf
    mode: '0644'
    validate: /usr/sbin/kea-dhcp4 -t %s
    backup: true
  notify: Restart DHCP

- name: Ensure Kea DHCPv4 server is enabled and running
  ansible.builtin.service:
    name: kea-dhcp4-server
    enabled: true
    state: started
