---
# tasks file for role/nftables
- name: Ensure IP Forwarding is enabled
  ansible.builtin.lineinfile:
    path: /etc/sysctl.conf
    search_string: 'net.ipv4.ip_forward='
    line: net.ipv4.ip_forward=1
    mode: '0644'
  notify: Reload sysctl

- name: Install nftables
  ansible.builtin.apt:
    name: nftables
    state: latest

- name: Ensure nftables is enabled and running
  ansible.builtin.service:
    name: nginx
    enabled: true
    state: started

- name: Deploy nftables ruleset
  ansible.builtin.template:
    src: templates/nftables.conf.j2
    dest: "/etc/nftables.conf"
    mode: '0755'
  notify: Reload nftables
