galaxy_info:
  author: Andrea Perotti <aperotti@pcofficina.org>
  description: Pcofficina.Netinstaller NFS Role
  company: Associazione PCOfficina

  # If the issue tracker for your role is not on github, uncomment the
  # next line and provide a value
  # issue_tracker_url: http://example.com/issue/tracker

  license: GPL-3.0-only

  min_ansible_version: "2.14"

  # If this a Container Enabled role, provide the minimum Ansible Container version.
  # min_ansible_container_version:

  platforms:
    - name: EL # Example, adjust based on geerlingguy.nfs compatibility
      versions:
        - "8"
        - "9"
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: Debian
      versions:
        - buster
        - bullseye

  galaxy_tags:
    - nfs
    - storage

dependencies:
  - role: pcofficina.netinstaller.common_vars
